# Generated by Django 2.1.5 on 2019-02-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
