# Generated by Django 2.1.5 on 2019-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_book_current_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.IntegerField(blank='True', default=0),
        ),
    ]
