# Generated by Django 2.1.5 on 2019-02-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190207_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
