# Generated by Django 2.1.5 on 2019-02-08 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190207_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.TextField())]),
        ),
    ]
