# Generated by Django 2.1.5 on 2019-02-08 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190207_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.IntegerField())]),
        ),
    ]
