# Generated by Django 2.1.5 on 2019-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190207_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
