# Generated by Django 2.1.5 on 2019-02-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
